# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141e133a5cf9214a8d8173fc9aaafa422f1393cffeaaabd12973782c0744f6e0aabc56294eceb793d2125d9e66e90ba467dd42e9c468505af2fc2405a35ead60

test:
  secret_key_base: 62ae806a555164e09993299db50b2d4f09681d414416bd48a369d3aa5a67f2360b378806cac6a3e56b623c75db5a024cf7da34c260205a3af5e7c2a541827092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
